### PR TITLE
Pure go lineintofile

### LINKED ISSUE #55: LineIntoFile needs exec.Sudo(h)
Hi,

I'm using v0.13.0-rc.2 of the k0sctl installer.

Installing k0s with k0sctl via ssh with a non-root user fails with:

DEBU[0000] [ssh] host:22: executing `/bin/bash -c -- 'file=/etc/environment; match='^NO_PROXY='; line=NO_PROXY=xyz; grep -q "${match}" "$file" && sed -i "/${match}/c ${line}" -- "$file" || (echo "$line" | tee -a -- "$file" > /dev/null)'` 
DEBU[0000] [ssh] host:22: (stderr) tee: /etc/environment: Permission denied

I think the problem is that it's not called with sudo here:
https://github.com/k0sproject/rig/blob/2c26742d00d1a83d9be783d03c0a9293bd8816a0/os/linux.go#L238

adding , exec.Sudo(h) to the end will probably fix the problem.

thanks,
Alex.

### PR DESCRIPTION
**Pull request by kke**
Closes #57 
Fixes #55

### CODE REVIEW

File: os/linux.go [hunk 1]
```diff
@@ -231,17 +232,35 @@ func (c Linux) FileExist(h Host, path string) bool {
 	return h.Execf(`test -e %s 2> /dev/null`, escape.Quote(path), exec.Sudo(h)) == nil
 }
 
-// LineIntoFile tries to find a matching line in a file and replace it with a new entry
-// TODO refactor this into go because it's too magical.
+// LineIntoFile tries to find a line starting with the matcher and replace it with a new entry. If match isn't found, the string is appended to the file.
+// TODO add exec.Opts (requires modifying readfile and writefile signatures)
 func (c Linux) LineIntoFile(h Host, path, matcher, newLine string) error {
```
Comment (twz123) [inline os/linux.go:237]: Now that this method is no longer a "remote" method, I wonder if it should still remain part of rig in the first place. The use case is also quite narrowed down to k0sctl's needs, I'd say.

**Comment by kke** [comment]
> btw, I'm pretty sure that I didn't author [987b23f](https://github.com/k0sproject/rig/commit/987b23fda6d13c93b7d8f99189c9435b46e3f23b) :-)

Some weird result of rebasing, I branched from the #56 fork and then rebased on top of main 🤔

File: os/linux.go (hunk 1 above)
Comment (kke) [reply os/linux.go:237]: Yeah maybe. I was also thinking that rig should have readfile + writefile that would use io.Reader / io.Writer. In that case it could do read => modify => write in two streams without reading the whole thing in memory at once. Launchpad also uses lineintofile but has implemented it locally.

There's still probably some simpler way to do the shell version. I don't like the copypaste here but didn't find a pleasing way to share such stuff between the os modules.
